server:
  port: ${PORT:8081}
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@saasmanagemnet.w5rw1.mongodb.net/mydatabase?retryWrites=true&w=majority&ssl=true
  application:
    name: saasmanagemnet

logging:
  level:
    root: DEBUG
